name: NotionJAM

on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: notion-jam
        uses: dimasma0305/notion-jam@v1.0.0
        with:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE: cc2cf42cf4b74db1901b8e28d3f67a06
          FILTER_PROP: ""
          FILTER_VALUES: ""
          CONVERT_PROP_CASE: snake
          ARTICLE_PATH: posts/{title}/README.md
          ASSETS_PATH: ./imgs
          PARALLEL_PAGES: 25
          PARALLEL_DOWNLOADS_PER_PAGE: 3
          DOWNLOAD_IMAGE_TIMEOUT: 30
          SKIP_DOWNLOADED_IMAGES: true
          DOWNLOAD_FRONTMATTER_IMAGES: true
      
      - name: Save changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes
          github_token: ${{ secrets.PERSONAL_TOKEN }}